config/routes.rb
GirlScouts::Application.routes.draw do
  get "welcome/index"
  get "scouts/report_on_everything"
  resources :tests

  resources :requirements

  resources :badges

  resources :scouts

  resources :specialities

  resources :leaders

  resources :addresses

  resources :organizations

  resources :chapters

  resources :users

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :organization
end

app/models/badge.rb
class Badge < ActiveRecord::Base
    has_and_belongs_to_many :scouts
    has_many: requirements, :as => :goal
end

app/models/badges_scout.rb
class BadgesScout < ActiveRecord::Base
  attr_accessible :badge_id, :scout_id
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
end

app/models/leader.rb
class Leader < ActiveRecord::Base
  belongs_to :chapter
  has_many :scouts
  has_one :chapter
  has_many :specialties
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :addresses
  has_many :chapters
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  belongs_to:goal, :polymorphic => true
end

app/models/scout.rb
class Scout < ActiveRecord::Base
  has_and_belongs_to_many :badges
  has_many :leaders
  belongs_to :chapter
end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
  has_many :leaders
  has_many: requirements, :as -> :goal
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  attr_accessible :name
  has_many :leaders
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @badge }
      else
        format.html { render action: 'new' }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:badge_name)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/leaders_helper.rb
module LeadersHelper
end

app/helpers/scouts_helper.rb
module ScoutsHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :badge_name %><br>
    <%= f.text_field :badge_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<h1>Listing badges</h1>

<table>
  <thead>
    <tr>
      <th>Badge name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= badge.badge_name %></td>
        <td><%= link_to 'Show', badge %></td>
        <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
        <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Badge', new_badge_path %>

app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Badge name:</strong>
  <%= @badge.badge_name %>
</p>

<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>