config/routes.rb
GirlScouts::Application.routes.draw do
  get "welcome/index"
  get "scouts/report_on_everything"
  resources :tests

  resources :requirements

  resources :badges

  resources :scouts

  resources :specialities

  resources :leaders

  resources :addresses

  resources :organizations

  resources :chapters

  resources :users

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :organization
end

app/models/badge.rb
class Badge < ActiveRecord::Base
    has_and_belongs_to_many :scouts
    has_many: requirements, :as => :goal
end

app/models/badges_scout.rb
class BadgesScout < ActiveRecord::Base
  attr_accessible :badge_id, :scout_id
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
end

app/models/leader.rb
class Leader < ActiveRecord::Base
  belongs_to :chapter
  has_many :scouts
  has_one :chapter
  has_many :specialties
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :addresses
  has_many :chapters
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  belongs_to:goal, :polymorphic => true
end

app/models/scout.rb
class Scout < ActiveRecord::Base
  has_and_belongs_to_many :badges
  has_many :leaders
  belongs_to :chapter
end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
  has_many :leaders
  has_many: requirements, :as -> :goal
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  attr_accessible :name
  has_many :leaders
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/scouts_controller.rb
class ScoutsController < ApplicationController
  #before_action :set_scout, only: [:show, :edit, :update, :destroy]

  # GET /scouts
  # GET /scouts.json
  def index
    @scouts = Scout.all
  end
  def report_on_everything
  end
  # GET /scouts/1
  # GET /scouts/1.json
  def show
  end

  # GET /scouts/new
  def new
    @scout = Scout.new
  end

  # GET /scouts/1/edit
  def edit
  end

  # POST /scouts
  # POST /scouts.json
  def create
    @scout = Scout.new(scout_params)

    respond_to do |format|
      if @scout.save
        format.html { redirect_to @scout, notice: 'Scout was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scout }
      else
        format.html { render action: 'new' }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scouts/1
  # PATCH/PUT /scouts/1.json
  def update
    respond_to do |format|
      if @scout.update(scout_params)
        format.html { redirect_to @scout, notice: 'Scout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scouts/1
  # DELETE /scouts/1.json
  def destroy
    @scout.destroy
    respond_to do |format|
      format.html { redirect_to scouts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scout
      @scout = Scout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scout_params
      params.require(:scout).permit(:first_name, :last_name, :member_since, :leader_id, :chapter_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/leaders_helper.rb
module LeadersHelper
end

app/helpers/scouts_helper.rb
module ScoutsHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/scouts/_form.html.erb
<%= form_for(@scout) do |f| %>
  <% if @scout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scout.errors.count, "error") %> prohibited this scout from being saved:</h2>

      <ul>
      <% @scout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :member_since %><br>
    <%= f.number_field :member_since %>
  </div>
  <div class="field">
    <%= f.label :leader_id %><br>
    <%= f.number_field :leader_id %>
  </div>
  <div class="field">
    <%= f.label :chapter_id %><br>
    <%= f.number_field :chapter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scouts/edit.html.erb
<h1>Editing scout</h1>

<%= render 'form' %>

<%= link_to 'Show', @scout %> |
<%= link_to 'Back', scouts_path %>

app/views/scouts/index.html.erb
<h1>Listing scouts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Member since</th>
      <th>Leader</th>
      <th>Chapter</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scouts.each do |scout| %>
      <tr>
        <td><%= scout.first_name %></td>
        <td><%= scout.last_name %></td>
        <td><%= scout.member_since %></td>
        <td><%= scout.leader_id %></td>
        <td><%= scout.chapter_id %></td>
        <td><%= link_to 'Show', scout %></td>
        <td><%= link_to 'Edit', edit_scout_path(scout) %></td>
        <td><%= link_to 'Destroy', scout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scout', new_scout_path %>

app/views/scouts/new.html.erb
<h1>New scout</h1>

<%= render 'form' %>

<%= link_to 'Back', scouts_path %>

app/views/scouts/report_on_everything.html.erb
TEST.
<h1>Report</h1>
<% Organization.all.each do |organization| %>
	<h2><%= organization.organization_name %></h2>
	<%= organization.chapters.each do |chapter| %>
		<h3><%= chapter.name %></h3>
			<h4><%= chapter.leaders.each do |leader|%></h4>
				<h5><%= leader.first_name%></h5>
			<% end %>
		<% end %>
	<% end%>

app/views/scouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @scout.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @scout.last_name %>
</p>

<p>
  <strong>Member since:</strong>
  <%= @scout.member_since %>
</p>

<p>
  <strong>Leader:</strong>
  <%= @scout.leader_id %>
</p>

<p>
  <strong>Chapter:</strong>
  <%= @scout.chapter_id %>
</p>

<%= link_to 'Edit', edit_scout_path(@scout) %> |
<%= link_to 'Back', scouts_path %>