config/routes.rb
GirlScouts::Application.routes.draw do
  get "welcome/index"
  get "scouts/report_on_everything"
  resources :tests

  resources :requirements

  resources :badges

  resources :scouts

  resources :specialities

  resources :leaders

  resources :addresses

  resources :organizations

  resources :chapters

  resources :users

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :organization
end

app/models/badge.rb
class Badge < ActiveRecord::Base
    has_and_belongs_to_many :scouts
    has_many: requirements, :as => :goal
end

app/models/badges_scout.rb
class BadgesScout < ActiveRecord::Base
  attr_accessible :badge_id, :scout_id
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
end

app/models/leader.rb
class Leader < ActiveRecord::Base
  belongs_to :chapter
  has_many :scouts
  has_one :chapter
  has_many :specialties
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :addresses
  has_many :chapters
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  belongs_to:goal, :polymorphic => true
end

app/models/scout.rb
class Scout < ActiveRecord::Base
  has_and_belongs_to_many :badges
  has_many :leaders
  belongs_to :chapter
end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
  has_many :leaders
  has_many: requirements, :as -> :goal
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  attr_accessible :name
  has_many :leaders
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/badges_scouts_controller.rb
class BadgesScoutsController < ApplicationController
  # GET /badges_scouts
  # GET /badges_scouts.json
  def index
    @badges_scouts = BadgesScout.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @badges_scouts }
    end
  end

  # GET /badges_scouts/1
  # GET /badges_scouts/1.json
  def show
    @badges_scout = BadgesScout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @badges_scout }
    end
  end

  # GET /badges_scouts/new
  # GET /badges_scouts/new.json
  def new
    @badges_scout = BadgesScout.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @badges_scout }
    end
  end

  # GET /badges_scouts/1/edit
  def edit
    @badges_scout = BadgesScout.find(params[:id])
  end

  # POST /badges_scouts
  # POST /badges_scouts.json
  def create
    @badges_scout = BadgesScout.new(params[:badges_scout])

    respond_to do |format|
      if @badges_scout.save
        format.html { redirect_to @badges_scout, notice: 'Badges scout was successfully created.' }
        format.json { render json: @badges_scout, status: :created, location: @badges_scout }
      else
        format.html { render action: "new" }
        format.json { render json: @badges_scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /badges_scouts/1
  # PUT /badges_scouts/1.json
  def update
    @badges_scout = BadgesScout.find(params[:id])

    respond_to do |format|
      if @badges_scout.update_attributes(params[:badges_scout])
        format.html { redirect_to @badges_scout, notice: 'Badges scout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @badges_scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges_scouts/1
  # DELETE /badges_scouts/1.json
  def destroy
    @badges_scout = BadgesScout.find(params[:id])
    @badges_scout.destroy

    respond_to do |format|
      format.html { redirect_to badges_scouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/badges_scouts_helper.rb
module BadgesScoutsHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/leaders_helper.rb
module LeadersHelper
end

app/helpers/scouts_helper.rb
module ScoutsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/badges_scouts/_form.html.erb
<%= form_for(@badges_scout) do |f| %>
  <% if @badges_scout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badges_scout.errors.count, "error") %> prohibited this badges_scout from being saved:</h2>

      <ul>
      <% @badges_scout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scout_id %><br />
    <%= f.number_field :scout_id %>
  </div>
  <div class="field">
    <%= f.label :badge_id %><br />
    <%= f.number_field :badge_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges_scouts/edit.html.erb
<h1>Editing badges_scout</h1>

<%= render 'form' %>

<%= link_to 'Show', @badges_scout %> |
<%= link_to 'Back', badges_scouts_path %>

app/views/badges_scouts/index.html.erb
<h1>Listing badges_scouts</h1>

<table>
  <tr>
    <th>Scout</th>
    <th>Badge</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @badges_scouts.each do |badges_scout| %>
  <tr>
    <td><%= badges_scout.scout_id %></td>
    <td><%= badges_scout.badge_id %></td>
    <td><%= link_to 'Show', badges_scout %></td>
    <td><%= link_to 'Edit', edit_badges_scout_path(badges_scout) %></td>
    <td><%= link_to 'Destroy', badges_scout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Badges scout', new_badges_scout_path %>

app/views/badges_scouts/new.html.erb
<h1>New badges_scout</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_scouts_path %>

app/views/badges_scouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Scout:</b>
  <%= @badges_scout.scout_id %>
</p>

<p>
  <b>Badge:</b>
  <%= @badges_scout.badge_id %>
</p>


<%= link_to 'Edit', edit_badges_scout_path(@badges_scout) %> |
<%= link_to 'Back', badges_scouts_path %>