config/routes.rb
GirlScouts::Application.routes.draw do
  get "welcome/index"
  get "scouts/report_on_everything"
  resources :tests

  resources :requirements

  resources :badges

  resources :scouts

  resources :specialities

  resources :leaders

  resources :addresses

  resources :organizations

  resources :chapters

  resources :users

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :organization
end

app/models/badge.rb
class Badge < ActiveRecord::Base
    has_and_belongs_to_many :scouts
    has_many: requirements, :as => :goal
end

app/models/badges_scout.rb
class BadgesScout < ActiveRecord::Base
  attr_accessible :badge_id, :scout_id
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
end

app/models/leader.rb
class Leader < ActiveRecord::Base
  belongs_to :chapter
  has_many :scouts
  has_one :chapter
  has_many :specialties
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :addresses
  has_many :chapters
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  belongs_to:goal, :polymorphic => true
end

app/models/scout.rb
class Scout < ActiveRecord::Base
  has_and_belongs_to_many :badges
  has_many :leaders
  belongs_to :chapter
end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
  has_many :leaders
  has_many: requirements, :as -> :goal
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  attr_accessible :name
  has_many :leaders
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @organization }
      else
        format.html { render action: 'new' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:organization_name)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/leaders_helper.rb
module LeadersHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/scouts_helper.rb
module ScoutsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organization_name %><br>
    <%= f.text_field :organization_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<table>
  <thead>
    <tr>
      <th>Organization name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.organization_name %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organization name:</strong>
  <%= @organization.organization_name %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>